package interfaz;

public class cancelar_reserva extends javax.swing.JFrame {

	/**
	 * Creates new form cancelar_reserva
	 */
	public cancelar_reserva() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		getContentPane().setLayout(null);

		jPanel1.setBackground(new java.awt.Color(212, 227, 252));
		jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		jPanel1.setLayout(null);

		jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
		jLabel1.setText("Esperamos que hayas disfrutado tu estadia. ");
		jPanel1.add(jLabel1);
		jLabel1.setBounds(50, 20, 370, 70);

		jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
		jLabel2.setText("Ingresa tu nombre para obtener");
		jLabel2.setToolTipText("");
		jPanel1.add(jLabel2);
		jLabel2.setBounds(90, 70, 300, 60);

		jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
		jLabel3.setText("la factura final.");
		jPanel1.add(jLabel3);
		jLabel3.setBounds(160, 120, 130, 30);

		jTextField1.setText("Nombre");
		jPanel1.add(jTextField1);
		jTextField1.setBounds(130, 180, 200, 30);

		jButton1.setBackground(new java.awt.Color(255, 249, 133));
		jButton1.setText("Ver factura");
		jPanel1.add(jButton1);
		jButton1.setBounds(180, 230, 110, 30);

		jButton2.setBackground(new java.awt.Color(255, 249, 133));
		jButton2.setText("Volver");
		jPanel1.add(jButton2);
		jButton2.setBounds(330, 280, 110, 30);

		getContentPane().add(jPanel1);
		jPanel1.setBounds(0, 0, 450, 320);

		pack();
	}// </editor-fold>

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException | InstantiationException | IllegalAccessException
				| javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(cancelar_reserva.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>

		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(() -> {
			new cancelar_reserva().setVisible(true);
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration
}
