package interfaz;


public class carga_Datos extends javax.swing.JFrame {

	    /**
	     * Creates new form Carga_Datos
	     */
	    public carga_Datos() {
	        initComponents();
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	    private void initComponents() {

	        jPanel1 = new javax.swing.JPanel();
	        jLabel1 = new javax.swing.JLabel();
	        jLabel2 = new javax.swing.JLabel();
	        jButton1 = new javax.swing.JButton();
	        jButton2 = new javax.swing.JButton();

	        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
	        getContentPane().setLayout(null);

	        jPanel1.setBackground(new java.awt.Color(212, 227, 252));
	        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
	        jPanel1.setLayout(null);

	        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
	        jLabel1.setText("El archivo a cargar,");
	        jPanel1.add(jLabel1);
	        jLabel1.setBounds(160, 110, 156, 23);

	        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
	        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
	        jLabel2.setText("ha sido cargado con éxito.");
	        jPanel1.add(jLabel2);
	        jLabel2.setBounds(130, 140, 220, 23);

	        jButton1.setBackground(new java.awt.Color(255, 249, 132));
	        jButton1.setText("Volver");
	        jPanel1.add(jButton1);
	        jButton1.setBounds(100, 190, 110, 30);

	        jButton2.setBackground(new java.awt.Color(255, 249, 132));
	        jButton2.setText("Cerrar Sesión");
	        jButton2.setToolTipText("");
	        jPanel1.add(jButton2);
	        jButton2.setBounds(260, 190, 110, 30);

	        getContentPane().add(jPanel1);
	        jPanel1.setBounds(0, 0, 458, 329);

	        pack();
	    }// </editor-fold>                        

	    /**
	     * @param args the command line arguments
	     */
	    public static void main(String args[]) {
	        /* Set the Nimbus look and feel */
	        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	         */
	        
	        //</editor-fold>

	        /* Create and display the form */
	        java.awt.EventQueue.invokeLater(new Runnable() {
	            public void run() {
	                new carga_Datos().setVisible(true);
	            }
	        });
	    }

	    // Variables declaration - do not modify                     
	    private javax.swing.JButton jButton1;
	    private javax.swing.JButton jButton2;
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JLabel jLabel2;
	    private javax.swing.JPanel jPanel1;
	    // End of variables declaration                   
	}

