package interfaz;

public class info_habitacion extends javax.swing.JFrame {

    /**
     * Creates new form info_habitacion
     */
    public info_habitacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(212, 227, 252));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel1.setText("Datos de habitación:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 0, 160, 20);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(170, 30, 190, 20);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(170, 60, 190, 20);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(170, 90, 190, 20);

        jTextField4.setToolTipText("");
        jPanel1.add(jTextField4);
        jTextField4.setBounds(170, 120, 190, 20);

        jButton1.setBackground(new java.awt.Color(255, 249, 132));
        jButton1.setText("Reservar");
        jPanel1.add(jButton1);
        jButton1.setBounds(30, 630, 110, 30);

        jButton2.setBackground(new java.awt.Color(255, 249, 132));
        jButton2.setText("Volver");
        jPanel1.add(jButton2);
        jButton2.setBounds(280, 630, 110, 30);

        jLabel2.setText("ID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 30, 12, 17);

        jLabel3.setText("TIPO");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 60, 28, 17);

        jLabel4.setText("CAPACIDAD");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 90, 80, 17);

        jLabel5.setText("TAMAÑO M2");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 120, 80, 17);

        jButton3.setBackground(new java.awt.Color(255, 249, 132));
        jButton3.setText("Volver a la lista");
        jPanel1.add(jButton3);
        jButton3.setBounds(150, 630, 120, 30);

        jLabel6.setText("UBICACIÓN");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 150, 80, 17);

        jLabel7.setText("VISTA");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 180, 34, 17);

        jLabel8.setText("BALCÓN");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(50, 210, 60, 17);

        jLabel9.setText("COCINA");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(50, 240, 50, 17);

        jLabel10.setText("AIRE ACON.");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(50, 270, 80, 17);

        jLabel11.setText("CALEFACCIÓN");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(50, 300, 90, 17);

        jLabel12.setText("TAMAÑO CAMA");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(50, 330, 100, 17);

        jLabel13.setText("TV");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(50, 360, 15, 17);

        jLabel14.setText("CAFETERA");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(50, 390, 70, 17);

        jLabel15.setText("ROPA DE CAMA");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(50, 420, 100, 17);

        jLabel16.setText("PLANCHA");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(50, 450, 70, 17);

        jLabel17.setText("SECADOR DE PELO");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(50, 480, 120, 17);

        jLabel18.setText("VOLTAJE AC");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(50, 510, 80, 17);

        jLabel19.setText("USB-A");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(50, 540, 39, 17);

        jLabel20.setText("USB-C");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(50, 570, 40, 17);

        jTextField5.setToolTipText("");
        jPanel1.add(jTextField5);
        jTextField5.setBounds(170, 120, 190, 20);

        jTextField6.setToolTipText("");
        jPanel1.add(jTextField6);
        jTextField6.setBounds(170, 150, 190, 20);

        jTextField7.setToolTipText("");
        jPanel1.add(jTextField7);
        jTextField7.setBounds(170, 180, 190, 20);

        jTextField8.setToolTipText("");
        jPanel1.add(jTextField8);
        jTextField8.setBounds(170, 210, 190, 20);

        jTextField9.setToolTipText("");
        jPanel1.add(jTextField9);
        jTextField9.setBounds(170, 240, 190, 20);

        jTextField10.setToolTipText("");
        jPanel1.add(jTextField10);
        jTextField10.setBounds(170, 270, 190, 20);

        jTextField11.setToolTipText("");
        jPanel1.add(jTextField11);
        jTextField11.setBounds(170, 300, 190, 20);

        jTextField12.setToolTipText("");
        jPanel1.add(jTextField12);
        jTextField12.setBounds(170, 330, 190, 20);

        jTextField13.setToolTipText("");
        jPanel1.add(jTextField13);
        jTextField13.setBounds(170, 360, 190, 20);

        jTextField14.setToolTipText("");
        jPanel1.add(jTextField14);
        jTextField14.setBounds(170, 390, 190, 20);

        jTextField15.setToolTipText("");
        jPanel1.add(jTextField15);
        jTextField15.setBounds(170, 420, 190, 20);

        jTextField16.setToolTipText("");
        jPanel1.add(jTextField16);
        jTextField16.setBounds(170, 450, 190, 20);

        jTextField17.setToolTipText("");
        jPanel1.add(jTextField17);
        jTextField17.setBounds(170, 480, 190, 20);

        jTextField18.setToolTipText("");
        jPanel1.add(jTextField18);
        jTextField18.setBounds(170, 510, 190, 20);

        jTextField19.setToolTipText("");
        jPanel1.add(jTextField19);
        jTextField19.setBounds(170, 540, 190, 20);

        jTextField20.setToolTipText("");
        jPanel1.add(jTextField20);
        jTextField20.setBounds(170, 570, 190, 20);

        jLabel21.setText("DESAYUNO");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(50, 600, 80, 17);

        jTextField21.setToolTipText("");
        jPanel1.add(jTextField21);
        jTextField21.setBounds(170, 600, 190, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 670);

        pack();
    }// </editor-fold>                        

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(info_habitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new info_habitacion().setVisible(true);
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration                   
}
