package interfaz;

import javax.swing.ImageIcon;

public class solicitar_servicio extends javax.swing.JFrame {

    /**
     * Creates new form solicitar_servicio
     */
    public solicitar_servicio() {
        initComponents();
        setSize(490, 390);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(212, 227, 252));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 249, 133));
        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel2.setText("¿Qué deseas ordenar?");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 10, 360, 30);

        jButton1.setBackground(new java.awt.Color(255, 249, 133));
        jButton1.setText("Platos");
        jPanel1.add(jButton1);
        jButton1.setBounds(90, 140, 110, 30);

        jButton2.setBackground(new java.awt.Color(255, 249, 133));
        jButton2.setText("Bebidas");
        jPanel1.add(jButton2);
        jButton2.setBounds(270, 140, 110, 30);

        jButton3.setBackground(new java.awt.Color(255, 249, 133));
        jButton3.setText("Spa");
        jPanel1.add(jButton3);
        jButton3.setBounds(90, 250, 110, 30);

        jButton4.setBackground(new java.awt.Color(255, 249, 133));
        jButton4.setText("Guia turistico");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(270, 250, 110, 30);

        jButton5.setBackground(new java.awt.Color(255, 249, 133));
        jButton5.setText("Volver");
        jPanel1.add(jButton5);
        jButton5.setBounds(330, 10, 110, 30);

        jLabel3.setIcon(new ImageIcon("./img/spa.jpg")); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(100, 160, 90, 100);

        jLabel4.setIcon(new ImageIcon("./img/plato.jpg")); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(110, 60, 80, 80);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("./img/bebidas-sin-alcohol.jpg"))); // NOI18N
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel5);
        jLabel5.setBounds(290, 60, 60, 70);

        jLabel6.setIcon(new ImageIcon("./img/turismo.jpg")); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(290, 180, 80, 70);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 450, 320);

        pack();
    }// </editor-fold>                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(solicitar_servicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new solicitar_servicio().setVisible(true);
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration                   
}
